version: '3.5'
services:
    app:
        image: hanabosocom/php-base:php-7.3-alpine
        user: ${DEV_UID}:${DEV_GID}
        environment:
            COMPOSER_HOME: ${HOME}/dev/.composer
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
            - ${HOME}/dev/.composer:${HOME}/dev/.composer
