services:
    app:
        image: hanabosocom/php-dev:php-8.4-alpine
        user: ${DEV_UID}:${DEV_GID}
        environment:
            COMPOSER_HOME: ${HOME}/dev/.composer
        volumes:
            - ./:/var/www:cached
            - ${HOME}/dev/.composer:${HOME}/dev/.composer:cached
