version: '3'
services:
    app:
        image: hanabosocom/php-base:php-7.3
        user: ${DEV_UID}:${DEV_GID}
        volumes:
            - ./:/var/www
            - ${SSH_AUTH_SOCK}:/tmp/bound-ssh-agent
